ci: add start app step

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -30,13 +30,20 @@ jobs:
       - name: Installer les dépendances
         run: |
           python -m pip install --upgrade pip
-          make install-dev
+          make install/dev
 
       - name: Lancer le lint
         run: make lint
 
       - name: Lancer le type check
         run: make type-check
+
+      - name: Build l'application
+        run: |
+          make start &
+          sleep 5
+          curl -f http://127.0.0.1:8000/health || (echo "App failed to start" && exit 1)
+          pkill -f "uvicorn"
 
       - name: Lancer les tests
         run: pytest -v
